[project]
name = "chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "emoji>=2.15.0",
    "seaborn>=0.13.2",
    "streamlit>=1.53.1",
    "textblob>=0.19.0",
    "wordcloud>=1.9.6",
]
